name: Deploy UI

on:
  push:
    tags:
      - 'ui-*'

concurrency:
  group: ui
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/snapfeed-ui
          TAG=${GITHUB_REF#refs/tags/}

          docker build -t $IMAGE:$TAG ./snapfeed-ui
          docker push $IMAGE:$TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SNAPFEED_EC2_HOST }}
          username: ${{ secrets.SNAPFEED_EC2_USERNAME }}
          key: ${{ secrets.SNAPFEED_EC2_KEY }}
          script: |
            TAG=${GITHUB_REF#refs/tags/}
            cd /home/ec2-user/SnapFeed

            export UI_TAG=$TAG

            docker-compose pull
            docker-compose up -d --force-recreate

            docker ps