# Generated by Django 6.0.3 on 2026-05-18 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0010_rename_hls_playlist_url_video_hls_playlist_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "SPAM"),
                            ("violence", "VIOLENCE"),
                            ("harassment", "HARASSMENT"),
                            ("hate_speech", "HATE_SPEECH"),
                            ("nudity", "NUDITY"),
                            ("copyright", "COPYRIGHT"),
                            ("misinformation", "MISINFORMATION"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("dismissed", "DISMISSED"),
                            ("action_taken", "ACTION_TAKEN"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("moderator_note", models.TextField(blank=True, default="")),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_video_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "db_table": "video_reports",
                "permissions": [("moderate_videoreport", "Can moderate video reports")],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="video_repor_status_dbbd18_idx",
                    ),
                    models.Index(
                        fields=["video", "status"],
                        name="video_repor_video_i_710bad_idx",
                    ),
                    models.Index(
                        fields=["reporter", "-created_at"],
                        name="video_repor_reporte_ac2d48_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reporter", "video"),
                        name="unique_reporter_video_report",
                    )
                ],
            },
        ),
    ]
