name: snapfeed-be

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: snapfeed-api
    container_name: snapfeed-api
    command: python -m daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    volumes:
      - .:/code
    ports:
      - "${MAPPING_API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: snapfeed-redis
    restart: unless-stopped
    ports:
      - "${MAPPING_REDIS_PORT:-6379}:6379"

  db:
    image: pgvector/pgvector:pg15
    container_name: snapfeed_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${MAPPING_DB_PORT}:5432"
    volumes:
      - data_snapfeed:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: snapfeed-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - "${MAPPING_ELASTIC_PORT}:9200"
    volumes:
      - data_elasticsearch:/usr/share/elasticsearch/data

volumes:
  data_snapfeed:
  data_elasticsearch:
