name: snapfeed-be

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: snapfeed-api
    container_name: snapfeed-api
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "${MAPPING_API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: snapfeed_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${MAPPING_DB_PORT}:5432"
    volumes:
      - data_snapfeed:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  data_snapfeed:
