name: snapfeed-fe

services:

  ui:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_DEFAULT_LANG: ${VITE_DEFAULT_LANG}
        VITE_FACEBOOK_APP_ID: ${VITE_FACEBOOK_APP_ID}
        VITE_FACEBOOK_AUTH_URL: ${VITE_FACEBOOK_AUTH_URL}
        VITE_FACEBOOK_REDIRECT_URI: ${VITE_FACEBOOK_REDIRECT_URI}
        VITE_GOOGLE_AUTH_URL: ${VITE_GOOGLE_AUTH_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_GOOGLE_REDIRECT_URI: ${VITE_GOOGLE_REDIRECT_URI}
        VITE_S3_BUCKET_URL: ${VITE_S3_BUCKET_URL}
    container_name: snapfeed-ui
    ports:
      - "${MAPPING_UI_PORT}:80"