# Generated by Django 6.0.3 on 2026-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_conversationparticipant_messageread_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[("direct", "DIRECT"), ("group", "GROUP"), ("self", "SELF")],
                default="direct",
                max_length=16,
            ),
        ),
    ]
