# Generated by Django 6.0.3 on 2026-04-13 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_alter_conversation_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="messages_sender__7f5f42_idx",
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="messages_sender__bf8b1c_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
    ]
