# Generated by Django 6.0.3 on 2026-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_remove_message_messages_sender__7f5f42_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("file", "File")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
