# Generated by Django 6.0.3 on 2026-05-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_message_attachment_key_message_attachment_name_and_more"),
        ("videos", "0010_rename_hls_playlist_url_video_hls_playlist_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="shared_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_messages",
                to="videos.video",
            ),
        ),
    ]
