# Generated by Django 6.0.3 on 2026-05-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_message_shared_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
