# Generated by Django 6.0.3 on 2026-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recommendation", "0002_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoembedding",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding",
                to="videos.video",
            ),
        ),
    ]
