# Generated by Django 6.0.3 on 2026-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendation",
            "0004_userembedding_videoembedding_video_embedding_hnsw_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userembedding",
            name="accumulated_weight",
            field=models.FloatField(default=0.0),
        ),
    ]
