apiVersion: v1
kind: ConfigMap
metadata:
  name: snapfeed-api-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-api
    {{- include "snapfeed.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.api.debug | quote }}
  DB_HOST: {{ .Values.postgres.host | quote }}
  DB_NAME: {{ .Values.postgres.dbName | quote }}
  DB_USER: {{ .Values.postgres.dbUser | quote }}
  MAPPING_API_PORT: {{ .Values.api.port | quote }}
  MAPPING_REDIS_PORT: {{ .Values.redis.port | quote }}
  MAPPING_ELASTIC_PORT: {{ .Values.elasticsearch.port | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  ELASTICSEARCH_HOST: {{ .Values.elasticsearch.url | quote }}
  ALLOWED_HOSTS: {{ .Values.api.allowedHosts | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.api.corsAllowedOrigins | quote }}
  APP_NAME: {{ .Values.api.appName | quote }}
  
  # OAuth2 URLs & App IDs
  GOOGLE_CLIENT_ID: {{ .Values.api.googleClientId | quote }}
  GOOGLE_REDIRECT_URI: {{ .Values.api.googleRedirectUri | quote }}
  GOOGLE_TOKEN_URL: {{ .Values.oauth.google.tokenUrl | quote }}
  FACEBOOK_APP_ID: {{ .Values.api.facebookAppId | quote }}
  FACEBOOK_REDIRECT_URI: {{ .Values.api.facebookRedirectUri | quote }}
  FACEBOOK_TOKEN_URL: {{ .Values.oauth.facebook.tokenUrl | quote }}
  FACEBOOK_USERINFO_URL: {{ .Values.oauth.facebook.userInfoUrl | quote }}
  CLIENT_HOMEPAGE_URL: {{ .Values.global.clientHomepageUrl | quote }}

  # AWS Integration
  AWS_STORAGE_BUCKET_NAME: {{ .Values.api.s3BucketName | quote }}
  AWS_DEFAULT_REGION: {{ .Values.global.awsRegion | quote }}
  SQS_QUEUE_URL: {{ .Values.api.sqsQueueUrl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: snapfeed-api-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-api
    {{- include "snapfeed.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.api.secretKey | quote }}
  DB_PASSWORD: {{ .Values.postgres.dbPassword | quote }}
  API_KEY: {{ .Values.api.apiKey | quote }}
  BASIC_AUTH_USERNAME: {{ .Values.api.basicAuthUsername | quote }}
  BASIC_AUTH_PASSWORD: {{ .Values.api.basicAuthPassword | quote }}
  SUPER_ADMIN_USERNAME: {{ .Values.api.superAdminUsername | quote }}
  SUPER_ADMIN_PASSWORD: {{ .Values.api.superAdminPassword | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.api.googleClientSecret | quote }}
  FACEBOOK_APP_SECRET: {{ .Values.api.facebookAppSecret | quote }}
