{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.api.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-api
    {{- include "snapfeed.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.api.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.api.roleArn | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.worker.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.worker.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-ai-worker
    {{- include "snapfeed.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.worker.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.worker.roleArn | quote }}
  {{- end }}
{{- end }}
