apiVersion: v1
kind: ConfigMap
metadata:
  name: snapfeed-worker-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-ai-worker
    {{- include "snapfeed.labels" . | nindent 4 }}
data:
  AWS_DEFAULT_REGION: {{ .Values.global.awsRegion | quote }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.api.s3BucketName | quote }}
  QUEUE_URL: {{ .Values.api.sqsQueueUrl | quote }}
  DOWNLOAD_DIR: {{ .Values.workerAi.downloadDir | quote }}
  MODEL_NAME: {{ .Values.workerAi.modelName | quote }}
  TEXT_MODEL_NAME: {{ .Values.workerAi.textModelName | quote }}
  BACKEND_CREATE_EMBEDDING_URL: {{ .Values.workerAi.createEmbeddingUrl | quote }}
  BACKEND_UPDATE_STATUS_URL: {{ .Values.workerAi.updateStatusUrl | quote }}
  BACKEND_GET_VIDEO_URL: {{ .Values.workerAi.getVideoUrl | quote }}
  NEED_HLS: "False"
  USE_EXTERNAL_HLS: "True"
---
apiVersion: v1
kind: Secret
metadata:
  name: snapfeed-worker-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-ai-worker
    {{- include "snapfeed.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.api.apiKey | quote }}
