# Generated by Django 6.0.3 on 2026-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_remove_notification_link_notification_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("react", "REACT"),
                    ("comment", "COMMENT"),
                    ("follow", "FOLLOW"),
                    ("system", "SYSTEM"),
                ],
                db_index=True,
                default="system",
                max_length=20,
            ),
        ),
    ]
