apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapfeed-ui
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-ui
    {{- include "snapfeed.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: snapfeed-ui
  template:
    metadata:
      labels:
        app: snapfeed-ui
    spec:
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ui.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: snapfeed-ui-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: snapfeed-ui
    {{- include "snapfeed.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: snapfeed-ui
  ports:
  - port: {{ .Values.ui.port }}
    targetPort: {{ .Values.ui.port }}
