listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=13.228.18.92
min-port=49152
max-port=65535
lt-cred-mech
user=snapuser:0xf55b21e9380b85a4b1c76eedd1813dad
realm=snapfeed.cloud
log-file=stdout
no-tls
no-dtls
