# Generated by Django 6.0.3 on 2026-03-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_remove_video_thumbnail_url_remove_video_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
