# Generated by Django 6.0.3 on 2026-03-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_video_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_url",
            new_name="video_key",
        ),
    ]
