# Generated by Django 6.0.3 on 2026-03-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_rename_video_url_video_video_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "permissions": [
                    ("generate_presigned_url", "Can generate presigned URL for video")
                ]
            },
        ),
    ]
