# Generated by Django 6.0.3 on 2026-04-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_alter_video_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "permissions": [
                    ("generate_presigned_url", "Can generate presigned URL for video"),
                    ("react_video", "Can react video."),
                ]
            },
        ),
    ]
