# Generated by Django 6.0.3 on 2026-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_alter_video_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="videos", to="videos.tag"
            ),
        ),
    ]
