# Generated by Django 6.0.3 on 2026-04-26 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_tag_video_title_video_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="thumbnails/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
