# Generated by Django 6.0.3 on 2026-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_alter_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="hls_playlist_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "PROCESSING"),
                    ("ready", "READY"),
                    ("failed", "FAILED"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
