# Generated by Django 6.0.3 on 2026-05-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_video_hls_playlist_url_video_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="hls_playlist_url",
            new_name="hls_playlist_key",
        ),
    ]
