# Generated by Django 6.0.3 on 2026-05-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
        ("videos", "0010_rename_hls_playlist_url_video_hls_playlist_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="music",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="music.music",
            ),
        ),
    ]
