name: Deploy worker-ai

on:
  push:
    tags:
      - 'worker-ai-*'

concurrency:
  group: worker-ai
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/snapfeed-ai-worker
          TAG=${GITHUB_REF#refs/tags/}
          docker build \
            -t "$IMAGE:$TAG" -t "$IMAGE:latest" \
            ./worker-ai
          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name sp --region ap-southeast-1

      - name: Deploy Worker AI with Helm
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          helm upgrade snapfeed ./helm/snapfeed -n snapfeed --reuse-values --set workerAi.image.tag=$TAG
